@extends('layouts.guest')

@section('title', 'Start Tracking')

@section('content')
    <div class="max-w-md mx-auto mt-20 p-6 bg-white rounded-2xl shadow-lg">
        <h1 class="text-2xl font-bold mb-6 text-center">Vehicle Tracking</h1>

        <p class="text-center text-gray-600 mb-8">
            Please log in or register to start sharing your location.
        </p>

        <div class="flex flex-col gap-4">
            <a href="{{ route('login') }}" class="block px-6 py-4 bg-indigo-600 text-white text-center rounded-xl hover:bg-indigo-700">
                Log In
            </a>
            <a href="{{ route('register') }}" class="block px-6 py-4 bg-gray-100 text-gray-800 text-center rounded-xl hover:bg-gray-200">
                Register
            </a>
        </div>

        <p class="mt-8 text-center text-sm text-gray-500">
            This link was generated by your fleet admin.
        </p>
    </div>
@endsection